packages:
  - packages/**
  - '!dist/**'

catalog:
  '@antfu/eslint-config': ^7.0.1
  '@iconify-json/carbon': ^1.2.18
  '@iconify-json/heroicons': ^1.2.3
  '@iconify-json/material-icon-theme': ^1.2.50
  '@iconify-json/material-symbols': ^1.2.55
  '@slidev/cli': ^52.11.3
  '@slidev/client': ^52.11.3
  '@slidev/theme-default': latest
  '@slidev/theme-seriph': ^0.25.0
  '@slidev/types': ^52.11.3
  '@types/fs-extra': ^11.0.4
  '@types/node': ^25.0.9
  '@types/prompts': ^2.4.9
  '@types/seedrandom': ^3.0.8
  '@vue/compiler-sfc': ^3.5.28
  eslint: ^9.39.2
  eslint-plugin-format: ^1.3.1
  execa: ^9.6.1
  fs-extra: ^11.3.3
  monaco-editor: ^0.55.1
  prompts: ^2.4.2
  rimraf: ^6.1.2
  seedrandom: ^3.0.5
  tsx: ^4.21.0
  typescript: ^5.9.3
  vue: ^3.5.26
  vue-tsc: ^3.2.4

catalogMode: prefer

onlyBuiltDependencies:
  - esbuild
  - playwright-chromium

shellEmulator: true
